### PR TITLE
FIX id mappings for included objects

### PR DESCRIPTION
**Pull request by nico-acidtango**
There's a bug when the top level id_key does not match with the one defined to render a children item.

For example, for an article document with serveral comments rendered using the following decorator

```ruby
class DocumentResourceWithDifferentIdAtRoot < Roar::Decorator
  include Roar::JSON::JSONAPI.resource :articles, id_key: :article_id

  attributes do
    property :title
    property :summary
  end

  has_many(:comments) do
    attributes do
      property :body
      property :good
    end
  end
end
```
You should expect to find a json such as:

```json
{
    "data": {
        "attributes": {
            "summary": "An interesting read.",
            "title": "My Article"
        },
        "id": "1",
        "relationships": {
            "comments": {
                "data": [
                    {
                        "id": "c:1",
                        "type": "comments"
                    },
                    {
                        "id": "c:2",
                        "type": "comments"
                    }
                ]
            }
        },
        "type": "articles"
    },
    "included": [
        {
            "attributes": {
                "body": "Cool!",
                "good": true
            },
            "id": "c:1",
            "type": "comments"
        },
        {
            "attributes": {
                "body": "Nah",
                "good": false
            },
            "id": "c:2",
            "type": "comments"
        }
    ]
}
```
but instead, the result obtained is:

```json
{
    "data": {
        "attributes": {
            "summary": "An interesting read.",
            "title": "My Article"
        },
        "id": "1",
        "relationships": {
            "comments": {
                "data": [
                    {
                        "id": "c:1",
                        "type": "comments"
                    },
                    {
                        "id": "c:2",
                        "type": "comments"
                    }
                ]
            }
        },
        "type": "articles"
    },
    "included": [
        {
            "attributes": {
                "body": "Cool!",
                "good": true
            },
            "type": "comments"
        }
    ]
}
```
And as such the included objects don't have the id key. This also affects collection rendering.

Something similar occurs when the situation is reversed and is the child decorator the one with a different id_key.

This pull request aims to fix this issue.

### CODE REVIEW

**Comment by rubenmoya** [comment]
Hi! Any update on this? Anything we could do to move forward with it?

**Comment by fran-worley** [comment]
@rubenmoya for good measure could we add a test for when the parent has a custom id_key and the child has a different custom id_key?

Sorry for the delay in looking at this, if we can get that extra test drawn up I'm happy to merge this unless @myabc has any strong feels...?

**Comment by acidtangodev** [comment]
Hi! Since we don't have access to the `nico-acidtango` account we opened a new PR based on his fork https://github.com/trailblazer/roar-jsonapi/pull/38, I think we can close this in favour of the other PR.

Thank you for your fast reply yesterday!

**Comment by fran-worley** [comment]
closing in favour of #38

**Pull request closed without merging**
